import type { VaultPatientIdentity } from '@/src/context/AppSyncProvider';
import type { ManagedPatientsStore } from '@/src/stores/managedPatientsStore';
import { validateBundleFreshness } from '@/src/lib/medical-sync-vault/crypto/bundleFreshness';
import { clearPatientLocalData } from '@/src/utils/clearPatientLocalData';

export type ManagedLinkRole = 'caregiver' | 'doctor';

/**
 * T-002 access bundle (V3).
 *
 * Generated by the PATIENT. Contains ONLY public material — no secret keys,
 * no transport_key, no medical_key. The recipient sends its own public keys
 * via the pre-auth rendezvous mailbox; the patient authorizes the recipient
 * device and wraps the transport_key back through the mailbox.
 */
export type ManagedAccessBundleV3 = {
    v: 3;
    subject_id: string;
    /** Patient's Ed25519 ROOT public key (public — for reference/verification). */
    patient_pubkey_b64: string;
    /** Random rendezvous token (mailbox id). */
    rendezvous_token: string;
    role: ManagedLinkRole;
    created_at: string;
};

function isUuid(value: string) {
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value ?? ''));
}

export function validateManagedAccessBundleV3(obj: unknown): obj is ManagedAccessBundleV3 {
    if (!obj || typeof obj !== 'object') return false;
    const bundle = obj as Partial<ManagedAccessBundleV3>;
    if (bundle.v !== 3) return false;
    if (!bundle.subject_id || !isUuid(bundle.subject_id)) return false;
    if (!bundle.patient_pubkey_b64 || String(bundle.patient_pubkey_b64).length < 8) return false;
    if (!bundle.rendezvous_token || String(bundle.rendezvous_token).length < 16) return false;
    if (!bundle.role || !['caregiver', 'doctor'].includes(bundle.role)) return false;
    if (!validateBundleFreshness(bundle.created_at)) return false;
    return true;
}

/** True for older (pre-T-002) bundle formats that carried secret keys. */
export function isOutdatedManagedAccessBundle(obj: unknown): boolean {
    if (!obj || typeof obj !== 'object') return false;
    const legacy = obj as { v?: unknown };
    return legacy.v === 1 || legacy.v === 2;
}

/**
 * Build a GRANTED VaultPatientIdentity from the recipient's OWN keypair plus the
 * unwrapped transport_key (received via rendezvous). No subject seckey, no medical key.
 */
export function grantedIdentity(args: {
    subjectId: string;
    ownPubkeyB64: string;
    ownSeckeyB64: string;
    transportKeyB64: string;
}): VaultPatientIdentity {
    return {
        patientId: args.subjectId,
        transportKeyB64: args.transportKeyB64,
        pubkeyB64: args.ownPubkeyB64,
        seckeyB64: args.ownSeckeyB64,
        mode: 'granted',
    };
}

/** Persist a granted patient (recipient's own keys + unwrapped transport_key). */
export async function upsertGrantedManagedPatient(
    managedPatientsStore: ManagedPatientsStore,
    args: { subjectId: string; ownPubkeyB64: string; ownSeckeyB64: string; transportKeyB64: string },
): Promise<void> {
    // Self-healing re-link: purge any stale local footprint for this subject BEFORE writing the
    // new grant. A previous grant may have left FHIR rows encrypted with the OLD transport_key
    // (e.g. after a revocation that wasn't cleaned up); without this, the new transport_key would
    // leave them undecryptable and corrupt the re-added patient.
    await clearPatientLocalData(args.subjectId).catch(() => {});
    await managedPatientsStore.remove(args.subjectId).catch(() => {});
    await managedPatientsStore.linkGranted(args.subjectId, {
        pubkeyB64: args.ownPubkeyB64,
        seckeyB64: args.ownSeckeyB64,
        transportKeyB64: args.transportKeyB64,
    });
}
